include:
  - project: $CI_PROJECT_NAMESPACE/metislab-core
    file: '.gitlab-ci.yml'
    ref: 'main'

variables:
  BASENAME: metislab-esa
  # Add DOCKER_BUILD_ARGS variable in CI/CD with value "--build-arg OCI_REGISTRY_PREFIX=<fill-here-your-CI_REGISTRY_IMAGE-prefix>/"
